### ISSUE TITLE
Fix logo

### ISSUE THREAD

**Issue by electronut** [electronut/beyond-arduino#2]
See attachment - the logo "Labs" juts out and does not look good.

Also, for silkscreen only logo, there is no need to dilate it.

<img width="765" alt="screen shot 2016-03-07 at 6 27 18 pm" src="https://cloud.githubusercontent.com/assets/3272706/13570112/4c7eb7d8-e492-11e5-976a-6f1604e785a7.png">

**Comment by rishi-electronut** [comment]
Ok sir. Shall fix it

**Comment by rishi-electronut** [comment]
logo fixed
